config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  # 前台展示
  get 'article_detail/:id', to: 'home#article_detail', as: :article_detail_home
  get 'article_detail/:id/like_records', to: 'home#like_article', as: :like_article_home
  get 'article_detail/:id/comments', to: 'home#article_comments', as: :article_detail_comments_home
  post 'article_detail/:id/comments', to: 'home#article_comment'

  get 'news', to: 'home#news', as: :news_home
  get 'news_detail/:id', to: 'home#news_detail', as: :news_detail_home
  get 'news_detail/:id/comments', to: 'home#news_comments', as: :news_detail_comments_home
  post 'news_detail/:id/comments', to: 'home#news_comment'


  # 后台管理
  namespace :admin do
    root "home#index"
    resources :templates, only: [:index] do
      collection do
        get :editor
      end
    end

    # 资讯管理
    namespace :news_manage do
      resources :news do

      end

      resources :tags do

      end

      resources :categories do

      end

      resources :comments do

      end

      resources :view_records do

      end

      resources :like_records do

      end
    end

    # 文章管理
    namespace :articles_manage do
      resources :articles do

      end

      resources :tags do

      end

      resources :categories do

      end

      resources :comments do

      end

      resources :view_records do

      end

      resources :like_records do

      end
    end

    # 用户管理
    namespace :users_manage do
      resources :users do

      end

      resources :roles do

      end

      resources :messages do

      end
    end

  end

end

app/models/news.rb
# == Schema Information
#
# Table name: news
#
#  id               :bigint(8)        not null, primary key
#  title            :string(255)
#  desp             :string(255)
#  content          :text(4294967295)
#  category_id      :bigint(8)
#  source_id        :bigint(8)
#  liked_counter    :integer          default(0)
#  viewed_counter   :integer          default(0)
#  comments_counter :integer          default(0)
#  status           :integer          default(0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class News < ApplicationRecord

  # ORM关系
  belongs_to :category, class_name: "Categories::MarkNews", foreign_key: :category_id
  belongs_to :source

  has_many :comments, class_name: "Comments::MarkNews", as: :subject
  has_many :like_records, class_name: "LikeRecords::MarkNews", as: :subject
  has_many :view_records, class_name: "ViewRecords::MarkNews", as: :subject
  has_many :subject_tags, as: :subject
  has_many :tags, class_name: "Tags::MarkNews", as: :subject, through: :subject_tags

  # scope
  scope :order_with_asc, -> (col){order("#{col} asc")}
  scope :order_with_desc, -> (col){order("#{col} desc")}
  scope :search, -> (keyword){where("title like ?", "%#{keyword}%")}
  scope :is_show_home, -> {where(status:1)}
  scope :where_with_time, ->(col,time){where("#{col} > ?", "#{time}")}
end

app/controllers/admin/news_manage/categories_controller.rb
class Admin::NewsManage::CategoriesController < Admin::BaseController
  before_action :find_one, only: [:edit, :update, :destroy]

  def index
    if params[:keyword].present?
      @categories = Categories::MarkNews.where("title like ?", "%#{params[:keyword]}%").order("created_at desc").page(params[:page]).per(LIST_PAGE)
    else
      @categories = Categories::MarkNews.order("created_at desc").page(params[:page]).per(LIST_PAGE)
    end
    @begin_count = (@categories.current_page - 1)*LIST_PAGE + 1
  end

  def new
    @category = Categories::MarkNews.new
  end

  def create
    @category = Categories::MarkNews.new(category_params)
    if @category.save
      redirect_to admin_news_manage_categories_path
      flash[:success] = "新增分类成功"
    else
      render :new
      flash[:error] = @category.errors.full_messages.join(",")
    end
  end

  def edit

  end

  def update
    @category.attributes = category_params
    if @category.save
      redirect_to admin_news_manage_categories_path
      flash[:success] = "更新分类成功"
    else
      render :edit
      flash[:error] = @article.errors.full_messages.join(",")
    end
  end

  def destroy
    if @category.update(status:-1)
      redirect_to admin_news_manage_categories_path
      flash[:success] = "删除分类成功"
    else
      flash[:error] = @category.errors.full_messages.join(",")
    end
  end

  private

    def find_one
      @category = Categories::MarkNews.find_by_id(params[:id])
    end

    def category_params
      params.require(:categories_mark_news).permit!
    end
end

app/controllers/admin/news_manage/comments_controller.rb
class Admin::NewsManage::CommentsController < Admin::BaseController
  before_action :find_one, only: [:edit, :update, :destroy]

  def index
    if params[:keyword].present?
      @comments = Comments::MarkNews.where("title like ?", "%#{params[:keyword]}%").order("created_at desc").page(params[:page]).per(LIST_PAGE)
    else
      @comments = Comments::MarkNews.order("created_at desc").page(params[:page]).per(LIST_PAGE)
    end
    @begin_count = (@comments.current_page - 1)*LIST_PAGE + 1
  end

  def new

  end

  def create
    @comment = Comments::MarkNews.new(comment_params)
    if @comment.save
      redirect_to admin_news_manage_comments_path
      flash[:success] = "新增评论成功"
    else
      render :new
      flash[:error] = @comment.errors.full_messages.join(",")
    end
  end

  def edit

  end

  def update
    @comment.attributes = comment_params
    if @comment.save
      redirect_to admin_news_manage_comments_path
      flash[:success] = "更新评论成功"
    else
      render :edit
      flash[:error] = @comment.errors.full_messages.join(",")
    end
  end

  def destroy
    if @comment.update(status:-1)
      redirect_to admin_news_manage_comments_path
      flash[:success] = "删除评论成功"
    else
      flash[:error] = @comment.errors.full_messages.join(",")
    end
  end

  private

    def find_one
      @comment = Comments::MarkNews.find_by_id(params[:id])
    end

    def comment_params
      params.require(:comment_mark_news).permit!
    end
end

app/controllers/admin/news_manage/like_records_controller.rb
class Admin::NewsManage::LikeRecordsController < Admin::BaseController
  before_action :find_one, only: [:edit, :update, :destroy]

  def index
    if params[:keyword].present?
      @like_records = LikeRecords::MarkNews.where("title like ?", "%#{params[:keyword]}%").order("created_at desc").page(params[:page]).per(LIST_PAGE)
    else
      @like_records =  LikeRecords::MarkNews.order("created_at desc").page(params[:page]).per(LIST_PAGE)
    end
    @begin_count = (@like_records.current_page - 1)*LIST_PAGE + 1
  end

  def new

  end

  def create
    @like_record = LikeRecords::MarkNews.new(like_record_params)
    if @like_record.save
      redirect_to admin_news_manage_like_records_path
      flash[:success] = "新增点赞记录成功"
    else
      render :new
      flash[:error] = @like_record.errors.full_messages.join(",")
    end
  end

  def edit

  end

  def update
    @like_record.attributes = like_record_params
    if @like_record.save
      redirect_to admin_news_manage_like_records_path
      flash[:success] = "更新点赞记录成功"
    else
      render :edit
      flash[:error] = @like_record.errors.full_messages.join(",")
    end
  end

  def destroy
    if @like_record.update(status:-1)
      redirect_to admin_news_manage_like_records_path
      flash[:success] = "删除点赞记录成功"
    else
      flash[:error] = @like_record.errors.full_messages.join(",")
    end
  end

  private
    def find_one
      @like_record = LikeRecords::MarkNews.find_by_id(params[:id])
    end

    def like_record_params
      params.require(:like_record_mark_news).permit!
    end
end

app/controllers/admin/news_manage/news_controller.rb
class Admin::NewsManage::NewsController < Admin::BaseController
  before_action :find_one, only: [:edit, :update, :destroy]
  before_action :find_categories,only: [:new,:create,:edit,:update]

  def index
    if params[:keyword].present?
      @all_news = News.includes(:tags,:source).search(params[:keyword]).order_with_desc("created_at").page(params[:page]).per(LIST_PAGE)
    else
      @all_news = News.includes(:tags,:source).order_with_desc("created_at").page(params[:page]).per(LIST_PAGE)
    end
    @begin_count = (@all_news.current_page - 1)*LIST_PAGE + 1
  end

  def new
    @article = News.new
  end

  def create
    @news = News.new(news_params.except(:tags))
    @news.tags = bind_tags
    if @news.save
      redirect_to admin_news_manage_news_index_path
      flash[:success] = "新增文章成功"
    else
      flash[:error] = @news.errors.full_messages.join(",")
      render :new
    end
  end

  def edit

  end

  def update
    @news.attributes = news_params.except(:tags)
    @news.tags = bind_tags
    if @news.save
      redirect_to admin_news_manage_news_index_path
      flash[:success] = "更新文章成功"
    else
      flash[:error] = @news.errors.full_messages.join(",")
      render :edit
    end
  end

  def destroy
    if @news.update(status:-1)
      redirect_to admin_news_manage_news_index_path
      flash[:success] = "删除文章成功"
    else
      flash[:error] = @news.errors.full_messages.join(",")
    end
  end

  private
  def find_one
    @news = News.find_by_id(params[:id])
  end

  def find_categories
    @categories = Categories::MarkNews.limit(50)
  end

  def bind_tags
    if !news_params[:tags].blank?
      tag_ids = []
      news_params[:tags].split(",").each do |tn|
        tag = Tags::MarkNews.find_or_create_by(name:tn)
        tag_ids << tag
      end
      tags = Tags::MarkNews.where(id:tag_ids)
    else
      tags = Tags::MarkNews.where(id:"")
    end
    tags
  end

  def news_params
    params.require(:news).permit!
  end
end

app/controllers/admin/news_manage/tags_controller.rb
class Admin::NewsManage::TagsController < Admin::BaseController
  before_action :find_one, only: [:edit, :update, :destroy]

  def index
    if params[:keyword].present?
      @tags = Tags::MarkNews.where("title like ?", "%#{params[:keyword]}%").order("created_at desc").page(params[:page]).per(LIST_PAGE)
    else
      @tags =  Tags::MarkNews.order("created_at desc").page(params[:page]).per(LIST_PAGE)
    end
    @begin_count = (@tags.current_page - 1)*LIST_PAGE + 1
  end

  def new
    @tag = Tags::MarkNews.new
  end

  def create
    @tag = Tags::MarkNews.new(tag_params)
    if @tag.save
      redirect_to admin_news_manage_tags_path
      flash[:success] = "新增标签成功"
    else
      render :new
      flash[:error] = @tag.errors.full_messages.join(",")
    end
  end

  def edit

  end

  def update
    @tag.attributes = tag_params
    if @tag.save
      redirect_to admin_news_manage_tags_path
      flash[:success] = "更新标签成功"
    else
      render :edit
      flash[:error] = @tag.errors.full_messages.join(",")
    end
  end

  def destroy
    if @tag.update(status:-1)
      redirect_to admin_news_manage_tags_path
      flash[:success] = "删除标签成功"
    else
      flash[:error] = @tag.errors.full_messages.join(",")
    end
  end

  private

    def find_one
      @tag = Tags::MarkNews.find_by_id(params[:id])
    end

    def tag_params
      params.require(:tags_mark_news).permit!
    end
end

app/controllers/admin/news_manage/view_records_controller.rb
class Admin::NewsManage::ViewRecordsController < Admin::BaseController
  before_action :find_one, only: [:edit, :update, :destroy]

  def index
    if params[:keyword].present?
      @view_records = ViewRecords::MarkNews.where("title like ?", "%#{params[:keyword]}%").order("created_at desc").page(params[:page]).per(LIST_PAGE)
    else
      @view_records =  ViewRecords::MarkNews.order("created_at desc").page(params[:page]).per(LIST_PAGE)
    end
    @begin_count = (@view_records.current_page - 1)*LIST_PAGE + 1
  end

  def new

  end

  def create
    @view_record = ViewRecords::MarkNews.new(view_record_params)
    if @view_record.save
      redirect_to admin_news_manage_view_records_path
      flash[:success] = "新增访问记录成功"
    else
      render :new
      flash[:error] = @view_record.errors.full_messages.join(",")
    end
  end

  def edit

  end

  def update
    @view_record.attributes = view_record_params
    if @view_record.save
      redirect_to admin_news_manage_view_records_path
      flash[:success] = "更新访问记录成功"
    else
      render :edit
      flash[:error] = @view_record.errors.full_messages.join(",")
    end
  end

  def destroy
    if @view_record.update(status:-1)
      redirect_to admin_news_manage_view_records_path
      flash[:success] = "删除访问记录成功"
    else
      flash[:error] = @view_record.errors.full_messages.join(",")
    end
  end

  private

    def find_one
      @view_record = ViewRecords::MarkNews.find_by_id(params[:id])
    end

    def view_record_params
      params.require(:view_record_mark_news).permit!
    end
end

app/helpers/news_manage/categories_helper.rb
module NewsManage::CategoriesHelper
end

app/helpers/news_manage/comments_helper.rb
module NewsManage::CommentsHelper
end

app/helpers/news_manage/like_records_helper.rb
module NewsManage::LikeRecordsHelper
end

app/helpers/news_manage/news_helper.rb
module NewsManage::NewsHelper
end

app/helpers/news_manage/tags_helper.rb
module NewsManage::TagsHelper
end

app/helpers/news_manage/view_records_helper.rb
module NewsManage::ViewRecordsHelper
end

app/views/admin/news_manage/news/_table.html.erb
<div class="row">
  <div class="col-xs-12">
    <table id="simple-table" class="table table-bordered table-hover">
      <thead>
      <tr>
        <th>#</th>
        <th class="detail-col">用户</th>
        <th>标题</th>
        <th>副标题</th>
        <th>内容</th>
        <th>
          <i class="ace-icon fa fa-clock-o bigger-110 hidden-480"></i>
          发布时间
        </th>
        <th class="hidden-480">评论人数</th>
        <th class="hidden-480">点赞人数</th>
        <th class="hidden-480">阅读人数</th>
        <th class="hidden-480">分类</th>
        <th class="hidden-480">标签</th>
        <th>是否展示</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% all_news.each do |news| %>
        <tr>
          <td class="center">
            <%= news.id %>
          </td>

          <td class="center">
            <div class="action-buttons">
              <a href="#" class="green bigger-140 show-details-btn" title="Show Details">
                <i class="ace-icon fa fa-angle-double-down"></i>
                <span class="sr-only">Details</span>
              </a>
            </div>
          </td>

          <td>
            <a href="#"><%= news.try(:title) %></a>
          </td>
          <td><%= news.try(:desp) %></td>
          <td><%= truncate(news.try(:content)) %></td>
          <td><%= format_time_yymmddhms(news.created_at) %></td>
          <td class="hidden-480"><%= news.try(:comments_counter) %></td>
          <td class="hidden-480"><%= news.try(:liked_counter) %></td>
          <td class="hidden-480"><%= news.try(:viewed_counter) %></td>
          <td class="hidden-480"><%= news.category.try(:name) if news.category.present? %></td>

          <td class="hidden-480">
            <% news.tags.each do |tag| %>
              <span class="label label-sm label-warning"><%= tag.try(:name) %></span>
            <% end %>
          </td>

          <td><%= news.status == 1 ? "是" : "否" %></td>

          <td>
            <div class="hidden-sm hidden-xs btn-group">
              <!--                    <button class="btn btn-xs btn-success">-->
              <!--                      <i class="ace-icon fa fa-check bigger-120"></i>-->
              <!--                    </button>-->

              <%= link_to edit_admin_news_manage_news_path(news) do %>
                <button class="btn btn-xs btn-info">
                  <i class="ace-icon fa fa-pencil bigger-120"></i>
                </button>
              <% end %>

              <%#= link_to admin_articles_manage_article_path(article),method: :delete do %>
              <button class="btn btn-xs btn-danger bootbox-confirm-delete" data-href="<%= admin_news_manage_news_path(article) %>">
                <i class="ace-icon fa fa-trash-o bigger-120"></i>
              </button>
              <%# end %>

              <!--                    <button class="btn btn-xs btn-warning">-->
              <!--                      <i class="ace-icon fa fa-flag bigger-120"></i>-->
              <!--                    </button>-->
            </div>
          </td>
        </tr>

      <% end %>
      </tbody>
    </table>
  </div><!-- /.span -->
</div><!-- /.row -->


<%= render partial: "kaminari/page_style", locals: { begin_count: begin_count, current_page: all_news , theme: "admin" }%>

app/views/admin/news_manage/news/edit.html.erb
<%= render("admin/news_manage/shares/header_breadcrumb") %>
<div class="page-content">
  <%= render("layout_shares/admin/setting_container") %>

  <div class="page-header">
    <h1>
      文章管理
      <small>
        <i class="ace-icon fa fa-angle-double-right"></i>
        编辑文章
      </small>
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <%= render("layout_shares/admin/alert") %>
      <!-- PAGE CONTENT BEGINS -->
      <%= form_for @article, url: edit_admin_news_manage_news_path,method: :put, html:{class: "form-horizontal" } do |f| %>

        <%= render partial: "admin/form_shares/f_chosen_select", locals: {f:f,field:"category_id",options: @categories.collect{|c|[c.name,c.id]},placeholder: "请选择分类", required:"true", selected: @article.category_id } %>

        <%= render partial: "admin/form_shares/f_text_field", locals: {f:f,field: "title", placeholder: "请输入文章标题", required:"true"} %>

        <%= render partial: "admin/form_shares/f_long_text_field", locals: {f:f,field: "desp", placeholder: "请输入文章副标题", required:""} %>

        <%= render partial: "admin/form_shares/editor", locals: {f:f,model:"article",field: "content",value:@article.content} %>

        <%= render partial: "admin/form_shares/f_tag_field", locals: {f:f,field: "tags",value: @article.tags.collect{|t|t.name}.join(","),placeholder: "请输入标签"} %>

        <%= render partial: "admin/form_shares/f_on_or_off_switches", locals: {f:f,field:"status"} %>



        <div class="clearfix form-actions">
          <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="submit">
              <i class="ace-icon fa fa-check bigger-110"></i>
              提交
            </button>

            &nbsp; &nbsp; &nbsp;
            <button class="btn" type="reset">
              <i class="ace-icon fa fa-undo bigger-110"></i>
              重置
            </button>
          </div>
        </div>

        <div class="hr hr-24"></div>
      <% end %>



    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.page-content -->

<%= render("admin/form_shares/f_js") %>

app/views/admin/news_manage/news/index.html.erb
<%= render("admin/news_manage/shares/header_breadcrumb") %>

<div class="page-content">
    <%= render("layout_shares/admin/setting_container") %>
  <!-- /.ace-settings-container -->

  <div class="page-header">
    <h1>
      资讯管理
      <small>
        <i class="ace-icon fa fa-angle-double-right"></i>
        资讯列表
      </small>
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <!-- PAGE CONTENT BEGINS -->
      <%= render("layout_shares/admin/alert") %>

      <a href="<%= new_admin_news_manage_news_path %>" class="btn btn-app btn-primary btn-xs radius-4">
        <i class="ace-icon fa fa-pencil-square-o bigger-160"></i>
        创建资讯
        <!--            <span class="badge badge-warning badge-left">11</span>-->
      </a>
      <div class="space"></div>

      <%= render partial: "table", locals: { all_news: @all_news, begin_count: @begin_count } %>


      <!-- PAGE CONTENT ENDS -->
    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.page-content -->

<%= render("admin/shares/table_js") %>

app/views/admin/news_manage/news/new.html.erb
<%= render("admin/news_manage/shares/header_breadcrumb") %>
<div class="page-content">
  <%= render("layout_shares/admin/setting_container") %>

  <div class="page-header">
    <h1>
      文章管理
      <small>
        <i class="ace-icon fa fa-angle-double-right"></i>
        写文章
      </small>
    </h1>
  </div><!-- /.page-header -->

  <div class="row">
    <div class="col-xs-12">
      <%= render("layout_shares/admin/alert") %>
      <!-- PAGE CONTENT BEGINS -->
      <%= form_for @article, url: admin_news_manage_news_index_path, html:{class: "form-horizontal" } do |f| %>

        <%= render partial: "admin/form_shares/f_chosen_select", locals: {f:f,field:"category_id",options: @categories.collect{|c|[c.name,c.id]},placeholder: "请选择分类", required:"true",selected: nil } %>

        <%= render partial: "admin/form_shares/f_text_field", locals: {f:f,field: "title", placeholder: "请输入资讯标题", required:"true"} %>

        <%= render partial: "admin/form_shares/f_long_text_field", locals: {f:f,field: "desp", placeholder: "请输入资讯副标题", required:""} %>

        <%= render partial: "admin/form_shares/editor", locals: {f:f,model:"article",field: "content", value: ""} %>

        <%= render partial: "admin/form_shares/f_tag_field", locals: {f:f,field: "tags",value: [].join(","),placeholder: "请输入标签"} %>

        <%= render partial: "admin/form_shares/f_on_or_off_switches", locals: {f:f,field:"status"} %>



        <div class="clearfix form-actions">
          <div class="col-md-offset-3 col-md-9">
            <button class="btn btn-info" type="submit">
              <i class="ace-icon fa fa-check bigger-110"></i>
              提交
            </button>

            &nbsp; &nbsp; &nbsp;
            <button class="btn" type="reset">
              <i class="ace-icon fa fa-undo bigger-110"></i>
              重置
            </button>
          </div>
        </div>

        <div class="hr hr-24"></div>
      <% end %>



    </div><!-- /.col -->
  </div><!-- /.row -->
</div><!-- /.page-content -->

<%= render("admin/form_shares/f_js") %>