config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  # 前台展示
  get 'article_detail/:id', to: 'home#article_detail', as: :article_detail_home
  get 'article_detail/:id/like_records', to: 'home#like_article', as: :like_article_home
  get 'article_detail/:id/comments', to: 'home#article_comments', as: :article_detail_comments_home
  post 'article_detail/:id/comments', to: 'home#article_comment'

  get 'news', to: 'home#news', as: :news_home
  get 'news_detail/:id', to: 'home#news_detail', as: :news_detail_home
  get 'news_detail/:id/comments', to: 'home#news_comments', as: :news_detail_comments_home
  post 'news_detail/:id/comments', to: 'home#news_comment'


  # 后台管理
  namespace :admin do
    root "home#index"
    resources :templates, only: [:index] do
      collection do
        get :editor
      end
    end

    # 资讯管理
    namespace :news_manage do
      resources :news do

      end

      resources :tags do

      end

      resources :categories do

      end

      resources :comments do

      end

      resources :view_records do

      end

      resources :like_records do

      end
    end

    # 文章管理
    namespace :articles_manage do
      resources :articles do

      end

      resources :tags do

      end

      resources :categories do

      end

      resources :comments do

      end

      resources :view_records do

      end

      resources :like_records do

      end
    end

    # 用户管理
    namespace :users_manage do
      resources :users do

      end

      resources :roles do

      end

      resources :messages do

      end
    end

  end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::BaseController
  def index

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "application"

  before_action :find_real_ip, only: [:article_detail, :like_article]
  before_action :find_article, only: [:article_detail, :like_article, :article_comments, :article_comment]
  before_action :find_like_record, only: [:article_detail]

  def index
    @articles = Article.includes(:tags,:user).is_show_home
    if params[:category_id].present?
      @articles = @articles.where(category_id:params[:category_id])
    end

    if params[:tag_id].present?
      @articles = @articles.joins(:tags).where(tags: {id: params[:tag_id]}).distinct
    end

    if params[:keyword].present?
      @articles = @articles.where("articles.title like ? articles.desp like ?", "#{params[:keyword]}", "#{params[:keyword]}")
    end

    @categories = Categories::MarkArticle.includes(:articles).is_show_home.limit(5)
    @new_articles = Article.is_show_home.order_with_desc("created_at").limit(5)
    @tags = Tags::MarkArticle.includes(:articles).is_show_home.limit(5)
    @articles = @articles.order_with_desc("articles.updated_at").page(params[:page]).per(LIST_PAGE)
    @begin_count = (@articles.current_page - 1)*LIST_PAGE + 1
  end

  def article_detail
    @article.view_records.create(user: @current_user, ip_address: @real_ip)
    @articles = Article.where_with_time("updated_at",@article.updated_at).limit(5)
    @new_articles = Article.is_show_home.order_with_desc("created_at").limit(5)
  end

  def like_article
    @article.like_records.create(user: @current_user, ip_address: @real_ip)
    redirect_to article_detail_home_path(@article)
  end

  def article_comments
    @comments = @article.comments.page(params[:page]).per(LIST_PAGE)
    @begin_count = (@comments.current_page - 1)*LIST_PAGE + 1
  end

  def article_comment
    @comment = @article.comments.new(comment_params)
    if @comment.save
      redirect_to article_detail_home_path(@article)
      flash[:success] = "评论成功"
    else
      redirect_to article_detail_home_path(@article)
      flash[:error] = "评论失败"
    end
  end

  def news

  end

  def news_comments

  end

  def news_comment

  end

  private
    def find_real_ip
      @real_ip = real_ip(request)
    end

    def find_article
      @article = Article.find_by_id(params[:id])
    end

    def find_like_record
      if @current_user.present?
        @like_record = @article.like_records.where(user_id:@current_user.id).first
      else
        @like_record = @article.like_records.where(ip_address: @real_ip).first
      end
    end

    def comment_params
      params.require(:comment).permit!
    end
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/article_detail.html.erb
<div class="col-xs-12 col-sm-8">
  <div class="page-header">
    <h4>记录学习的点点滴滴 <small>不积跬步无以至千里</small></h4>
  </div>
  <div class="content">
    <header class="article-header">
      <h1 class="article-title"><a href="#"><%= @article.try(:title) %></a></h1>
      <div class="article-meta ">
        <span class="item tags">来源：
          原创
        </span>
        <span class="item category">分类: &nbsp
          <a href="">
            <%=@article.category.present? ? @article.category.try(:name) : "暂无" %>
          </a>
        </span>
        <span class="item tags">标签：
          <% unless @article.tags.blank? %>
            <% @article.tags.each do |tag| %>
              <a href="">
                <%= tag.name %>
              </a>
            <% end %>
          <% else %>
            暂无标签
          <% end %>
        </span>
        <span class="item time "><i class="glyphicon glyphicon-time"></i> <%= @article.created_at.strftime("%Y-%m-%d") %></span>
        <span class="item likes">
          <% if @like_record.present? %>
            <i class="glyphicon glyphicon-heart"></i>
          <% else %>
            <%= link_to like_article_home_path(@article), class: "normal_font" do %>
              <i class="glyphicon glyphicon-heart-empty"></i>
            <% end %>
          <% end %>
          <%= @article.try(:liked_counter) %>
        </span>
        <span class="item views"><a class="normal_font" href="javascript:"><i class="glyphicon glyphicon-eye-open"></i></a> <%= @article.try(:viewed_counter) %></span>
        <span class="item comment"><a class="normal_font" href="javascript:"><i class="glyphicon glyphicon-comment"></i></a> <%= @article.try(:comments_counter) %></span>
      </div>
    </header>


    <div id="test-editormd-view2">
      <textarea id="append-test" style="display:none;"><%= @article.try(:content) %></textarea>
    </div>

    <!--        <div class="title">-->
    <!--          <h3>评论</h3>-->
    <!--        </div>-->
    <!--        <div class="article-comment">-->
    <!--          <form action="" method="POST">-->
    <!--            <input type="text" class="form-control" placeholder="您的昵称（必填）">-->
    <!--            <input type="text" class="form-control" placeholder="您的邮箱或联系电话（非必填）">-->
    <!--            <textarea class="form-control" rows="3" placeholder="您的评论或留言（必填）"></textarea>-->
    <!--            <button type="button" class="btn btn-default">发布评论</button>-->
    <!--          </form>-->
    <!--        </div>-->

    <!--        <div class="postcomments">-->
    <!--          <ol class="commentlist">-->
    <!--            <li class="comment-content"><span class="comment-f">#2</span>-->
    <!--              <div class="comment-main">-->
    <!--                <p><a class="name" href="#" target="_blank">zx@reedo.cn</a><span class="time"> 2016/10/28 11:41:03</span><br>不错的网站主题，看着相当舒服</p>-->
    <!--              </div>-->
    <!--            </li>-->
    <!--            <li class="comment-content"><span class="comment-f">#2</span>-->
    <!--              <div class="comment-main">-->
    <!--                <p><a class="name" href="#" target="_blank">九日</a><span class="time"> 2016/10/28 11:41:03</span><br>不错的网站主题，看着相当舒服</p>-->
    <!--              </div>-->
    <!--            </li>-->
    <!--          </ol>-->
    <!--        </div>-->
  </div>
</div><!--/.col-xs-12.col-sm-9-->

<div class="col-xs-12 col-sm-4">
  <%= render("layout_shares/article_detail_navbar") %>
</div><!--/.sidebar-offcanvas-->

<% content_for :extro_scripts do %>
  <script type="text/javascript">
      $(function() {
          var testEditormdView, testEditormdView2;

          testEditormdView2 = editormd.markdownToHTML("test-editormd-view2", {
              htmlDecode      : "style,script,iframe",  // you can filter tags decode
              emoji           : true,
              taskList        : true,
              tex             : true,  // 默认不解析
              flowChart       : true,  // 默认不解析
              sequenceDiagram : true,  // 默认不解析
          });
      });
  </script>
<% end %>

app/views/home/index.html.erb
<div class="col-xs-12 col-sm-8">
  <div class="page-header">
    <h4>记录学习的点点滴滴 <small>不积跬步无以至千里</small></h4>
  </div>
  <div class="content col-xs-12" style="margin-left: -15px;">
    <div class="title">
      <h3>最新发布</h3>
      <div class="more">
        <%= link_to "全部", root_path %>
        <% @categories.each do |category| %>
          <%= link_to category.try(:name), root_path(category_id:category.id,tag_id:params[:tag_id],create_time:params[:create_time]) %>
        <% end %>
      </div>
    </div>
    <% if @articles.blank?  %>
      <div class="excerpt">
        <%= image_tag("no_article.png",class: "img-responsive") %>
      </div>
    <% else %>
      <% @articles.each do |art| %>
        <div class="excerpt">
          <header>
            <%= link_to root_path(category_id:art.category_id),class:"cat" do %>
              <!--              <a class="cat" href="#">-->
              <%=art.category.present? ? art.category.try(:name) : "暂无" %> <i></i>
              <!--              </a>-->
            <% end %>
            <h2>
              <a href="/article_detail/<%= art.id %>">
                <%= art.try(:title) %>
              </a>
            </h2>
          </header>
          <p><%= art.try(:desp) %></p>
          <p class="meta">
            <a class="time" href="#"><i class="glyphicon glyphicon-time"></i> <%= art.created_at.strftime("%Y-%m-%d") %></a>
            <a class="likes" href="#"><i class="glyphicon glyphicon-heart-empty"></i> <%= art.try(:liked_counter) %></a>
            <a class="views" href="#"><i class="glyphicon glyphicon-eye-open"></i> <%= art.try(:viewed_counter) %></a>
            <a class="comment" href="#"><i class="glyphicon glyphicon-comment"></i> <%= art.try(:comments_counter) %></a>
          </p>
        </div>
      <% end %>
    <% end %>



<%= paginate @articles, theme: 'home' %>
  </div>
</div><!--/.col-xs-12.col-sm-9-->
<div class="col-xs-12 col-sm-4">
  <%= render("layout_shares/index_right_navbar") %>
</div><!--/.sidebar-offcanvas-->