config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords',
      registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  # 前台展示
  get 'article_detail/:id', to: 'home#article_detail', as: :article_detail_home
  get 'article_detail/:id/like_records', to: 'home#like_article', as: :like_article_home
  get 'article_detail/:id/comments', to: 'home#article_comments', as: :article_detail_comments_home
  post 'article_detail/:id/comments', to: 'home#article_comment'

  get 'news', to: 'home#news', as: :news_home
  get 'news_detail/:id', to: 'home#news_detail', as: :news_detail_home
  get 'news_detail/:id/comments', to: 'home#news_comments', as: :news_detail_comments_home
  post 'news_detail/:id/comments', to: 'home#news_comment'


  # 后台管理
  namespace :admin do
    root "home#index"
    resources :templates, only: [:index] do
      collection do
        get :editor
      end
    end

    # 资讯管理
    namespace :news_manage do
      resources :news do

      end

      resources :tags do

      end

      resources :categories do

      end

      resources :comments do

      end

      resources :view_records do

      end

      resources :like_records do

      end
    end

    # 文章管理
    namespace :articles_manage do
      resources :articles do

      end

      resources :tags do

      end

      resources :categories do

      end

      resources :comments do

      end

      resources :view_records do

      end

      resources :like_records do

      end
    end

    # 用户管理
    namespace :users_manage do
      resources :users do

      end

      resources :roles do

      end

      resources :messages do

      end
    end

  end

end

app/views/layout_shares/_admin_alert.html.erb
<% flash.each do |k,v| %>
  <% if k != "timedout" %>
    <% case k %>
    <% when "success" %>
      <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">
          <i class="ace-icon fa fa-times"></i>
        </button>
        <i class="glyphicon glyphicon-ok-sign"></i>
        <%= v %>
      </div>
    <% when "info" %>
      <div class="alert alert-block alert-info">
        <button type="button" class="close" data-dismiss="alert">
          <i class="ace-icon fa fa-times"></i>
        </button>
        <i class="glyphicon glyphicon-info-sign"></i>
        <%= v %>
      </div>
    <% when "error" %>
      <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">
          <i class="ace-icon fa fa-times"></i>
        </button>
        <i class="glyphicon glyphicon-remove-sign"></i>
        <%= v %>
      </div>
    <% end %>
  <% end %>
<% end %>
<% flash.clear %>

app/views/layout_shares/_admin_footer.html.erb
<div class="footer">
  <div class="footer-inner">
    <div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">Ace</span>
							Application &copy; 2013-2014
						</span>

      &nbsp; &nbsp;
      <span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
    </div>
  </div>
</div>

<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
  <i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
</a>

app/views/layout_shares/_admin_nav_list.html.erb
<ul class="nav nav-list">
  <li class="active">
    <a href="index.html">
      <i class="menu-icon fa fa-tachometer"></i>
      <span class="menu-text"> Dashboard </span>
    </a>

    <b class="arrow"></b>
  </li>

  <li class="">
    <a href="#" class="dropdown-toggle">
      <i class="menu-icon fa fa-desktop"></i>
      <span class="menu-text">
								UI &amp; Elements
							</span>

      <b class="arrow fa fa-angle-down"></b>
    </a>

    <b class="arrow"></b>

    <ul class="submenu">
      <li class="">
        <a href="#" class="dropdown-toggle">
          <i class="menu-icon fa fa-caret-right"></i>

          Layouts
          <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
          <li class="">
            <a href="top-menu.html">
              <i class="menu-icon fa fa-caret-right"></i>
              Top Menu
            </a>

            <b class="arrow"></b>
          </li>

          <li class="">
            <a href="two-menu-1.html">
              <i class="menu-icon fa fa-caret-right"></i>
              Two Menus 1
            </a>

            <b class="arrow"></b>
          </li>

          <li class="">
            <a href="two-menu-2.html">
              <i class="menu-icon fa fa-caret-right"></i>
              Two Menus 2
            </a>

            <b class="arrow"></b>
          </li>

          <li class="">
            <a href="mobile-menu-1.html">
              <i class="menu-icon fa fa-caret-right"></i>
              Default Mobile Menu
            </a>

            <b class="arrow"></b>
          </li>

          <li class="">
            <a href="mobile-menu-2.html">
              <i class="menu-icon fa fa-caret-right"></i>
              Mobile Menu 2
            </a>

            <b class="arrow"></b>
          </li>

          <li class="">
            <a href="mobile-menu-3.html">
              <i class="menu-icon fa fa-caret-right"></i>
              Mobile Menu 3
            </a>

            <b class="arrow"></b>
          </li>
        </ul>
      </li>

      <li class="">
        <a href="typography.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Typography
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="elements.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Elements
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="buttons.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Buttons &amp; Icons
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="content-slider.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Content Sliders
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="treeview.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Treeview
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="jquery-ui.html">
          <i class="menu-icon fa fa-caret-right"></i>
          jQuery UI
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="nestable-list.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Nestable Lists
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="#" class="dropdown-toggle">
          <i class="menu-icon fa fa-caret-right"></i>

          Three Level Menu
          <b class="arrow fa fa-angle-down"></b>
        </a>

        <b class="arrow"></b>

        <ul class="submenu">
          <li class="">
            <a href="#">
              <i class="menu-icon fa fa-leaf green"></i>
              Item #1
            </a>

            <b class="arrow"></b>
          </li>

          <li class="">
            <a href="#" class="dropdown-toggle">
              <i class="menu-icon fa fa-pencil orange"></i>

              4th level
              <b class="arrow fa fa-angle-down"></b>
            </a>

            <b class="arrow"></b>

            <ul class="submenu">
              <li class="">
                <a href="#">
                  <i class="menu-icon fa fa-plus purple"></i>
                  Add Product
                </a>

                <b class="arrow"></b>
              </li>

              <li class="">
                <a href="#">
                  <i class="menu-icon fa fa-eye pink"></i>
                  View Products
                </a>

                <b class="arrow"></b>
              </li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  </li>

  <li class="">
    <a href="#" class="dropdown-toggle">
      <i class="menu-icon fa fa-list"></i>
      <span class="menu-text"> Tables </span>

      <b class="arrow fa fa-angle-down"></b>
    </a>

    <b class="arrow"></b>

    <ul class="submenu">
      <li class="">
        <a href="tables.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Simple &amp; Dynamic
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="jqgrid.html">
          <i class="menu-icon fa fa-caret-right"></i>
          jqGrid plugin
        </a>

        <b class="arrow"></b>
      </li>
    </ul>
  </li>

  <li class="">
    <a href="#" class="dropdown-toggle">
      <i class="menu-icon fa fa-pencil-square-o"></i>
      <span class="menu-text"> Forms </span>

      <b class="arrow fa fa-angle-down"></b>
    </a>

    <b class="arrow"></b>

    <ul class="submenu">
      <li class="">
        <a href="form-elements.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Form Elements
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="form-elements-2.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Form Elements 2
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="form-wizard.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Wizard &amp; Validation
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="wysiwyg.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Wysiwyg &amp; Markdown
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="dropzone.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Dropzone File Upload
        </a>

        <b class="arrow"></b>
      </li>
    </ul>
  </li>

  <li class="">
    <a href="widgets.html">
      <i class="menu-icon fa fa-list-alt"></i>
      <span class="menu-text"> Widgets </span>
    </a>

    <b class="arrow"></b>
  </li>

  <li class="">
    <a href="calendar.html">
      <i class="menu-icon fa fa-calendar"></i>

      <span class="menu-text">
								Calendar

								<span class="badge badge-transparent tooltip-error" title="2 Important Events">
									<i class="ace-icon fa fa-exclamation-triangle red bigger-130"></i>
								</span>
							</span>
    </a>

    <b class="arrow"></b>
  </li>

  <li class="">
    <a href="gallery.html">
      <i class="menu-icon fa fa-picture-o"></i>
      <span class="menu-text"> Gallery </span>
    </a>

    <b class="arrow"></b>
  </li>

  <li class="">
    <a href="#" class="dropdown-toggle">
      <i class="menu-icon fa fa-tag"></i>
      <span class="menu-text"> More Pages </span>

      <b class="arrow fa fa-angle-down"></b>
    </a>

    <b class="arrow"></b>

    <ul class="submenu">
      <li class="">
        <a href="profile.html">
          <i class="menu-icon fa fa-caret-right"></i>
          User Profile
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="inbox.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Inbox
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="pricing.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Pricing Tables
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="invoice.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Invoice
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="timeline.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Timeline
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="search.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Search Results
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="email.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Email Templates
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="login.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Login &amp; Register
        </a>

        <b class="arrow"></b>
      </li>
    </ul>
  </li>

  <li class="">
    <a href="#" class="dropdown-toggle">
      <i class="menu-icon fa fa-file-o"></i>

      <span class="menu-text">
								Other Pages

								<span class="badge badge-primary">5</span>
							</span>

      <b class="arrow fa fa-angle-down"></b>
    </a>

    <b class="arrow"></b>

    <ul class="submenu">
      <li class="">
        <a href="faq.html">
          <i class="menu-icon fa fa-caret-right"></i>
          FAQ
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="error-404.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Error 404
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="error-500.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Error 500
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="grid.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Grid
        </a>

        <b class="arrow"></b>
      </li>

      <li class="">
        <a href="blank.html">
          <i class="menu-icon fa fa-caret-right"></i>
          Blank Page
        </a>

        <b class="arrow"></b>
      </li>
    </ul>
  </li>
</ul><!-- /.nav-list -->

<div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
  <i id="sidebar-toggle-icon" class="ace-icon fa fa-angle-double-left ace-save-state" data-icon1="ace-icon fa fa-angle-double-left" data-icon2="ace-icon fa fa-angle-double-right"></i>
</div>

app/views/layout_shares/_admin_sidebar_shortcuts.html.erb
<div class="sidebar-shortcuts" id="sidebar-shortcuts">
  <div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
    <button class="btn btn-success">
      <i class="ace-icon fa fa-signal"></i>
    </button>

    <button class="btn btn-info">
      <i class="ace-icon fa fa-pencil"></i>
    </button>

    <button class="btn btn-warning">
      <i class="ace-icon fa fa-users"></i>
    </button>

    <button class="btn btn-danger">
      <i class="ace-icon fa fa-cogs"></i>
    </button>
  </div>

  <div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
    <span class="btn btn-success"></span>

    <span class="btn btn-info"></span>

    <span class="btn btn-warning"></span>

    <span class="btn btn-danger"></span>
  </div>
</div><!-- /.sidebar-shortcuts -->

app/views/layout_shares/_article_detail_navbar.html.erb
<div class="sidebar ">
  <div class="widget widget_hot">
    <h3>文章目录</h3>
    <ul>
      <% @articles.each do |article| %>
        <li><a title="" href="/article_detail/<%=article.id %>"><span class="text"><%= article.try(:title) %></span></a></li>
      <% end %>
    </ul>
  </div>
  <div class="widget widget_hot ">
    <h3>最新文章</h3>
    <ul>
      <% @new_articles.each do |article| %>
        <li>
          <a title=" " href="# ">
            <span class="text "><%= article.try(:title) %></span>
            <span class="muted ">
                                              <i class="glyphicon glyphicon-time "></i>
                                              <%= format_time_yymmdd(article.created_at) %>
                                          </span>
            <span class="muted ">
                                              <i class="glyphicon glyphicon-eye-open "></i> <%= article.try(:viewed_counter) %></span>
          </a>
        </li>
      <% end %>
    </ul>
  </div>

</div>

app/views/layout_shares/_footer.html.erb
<div class="footer">
  <div class="container">
    <p>Copyright &copy; 2018.yystopf's blog All rights reserved</p>
  </div>
</div>

app/views/layout_shares/_header.html.erb
<header>
  <nav class="navbar navbar-default" id="navbar">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false">
          <span class="sr-only"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <h3 class="logo">
          <a href="/">vilet.yy的博客</a>
        </h3>
      </div>
      <div class="collapse navbar-collapse" id="header-navbar">
        <form class="navbar-form visible-xs" action="/" method="GET">
          <div class="input-group">
            <input type="text" name="keyword" class="form-control" placeholder="请输入关键字" maxlength="20" autocomplete="off">
            <span class="input-group-btn">
                                <button type="submit" class="btn btn-default btn-search">搜索</button>
                            </span>
          </div>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="/">首页</a></li>
<!--          <li><a href="#">博客</a></li>-->
<!--          <li><a href="#">技术分享</a></li>-->
<!--          <li><a href="#">关于</a></li>-->
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layout_shares/_index_right_navbar.html.erb
<div class="sidebar">
  <div class="widget widget_hot">
    <h3>最新文章</h3>
    <ul>
      <% unless @new_articles.blank? %>
        <% @new_articles.each do |art| %>
          <li>
            <a href="/article_detail/<%= art.id %>">
              <span class="text"><%= art.title %></span>
              <span class="muted">
                        <i class="glyphicon glyphicon-time"></i>
                <%= art.created_at.strftime("%Y-%m-%d") %>
                    </span>
              <span class="muted">
                        <i class="glyphicon glyphicon-eye-open"></i>  <%= art.try(:viewed_counter) %>
                    </span>
            </a>
          </li>
        <% end %>
      <% else %>
      <% end %>

    </ul>
  </div>
  <div class="widget widget_sentence">
    <h3>标签云</h3>
    <ul>
      <% @tags.each do |tag| %>
        <li>
          <%= link_to root_path(tag_id:tag.id) do %>
            <%= tag.try(:name) %> <span class="badge"><%= tag.articles.is_show_home.size %></span>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layout_shares/_right_navbar.html.erb
<div class="sidebar">
  <div class="widget widget_hot">
    <h3>最新文章</h3>
    <ul>
      <% unless @new_articles.blank? %>
        <% @new_articles.each do |art| %>
          <li>
<!--            <a title="" href="#">-->
            <%= link_to detail_home_path(id:art.id) do %>
              <span class="text"><%= art.title %></span>
              <span class="muted">
                        <i class="glyphicon glyphicon-time"></i>
                        <%= art.created_at.strftime("%Y-%m-%d") %>
                    </span>
              <span class="muted">
                        <i class="glyphicon glyphicon-eye-open"></i>  <%= art.try(:view_records_count) %>
                    </span>
            <% end %>
          </li>
        <% end %>
      <% else %>
      <% end %>

    </ul>
  </div>
  <div class="widget widget_category">
    <h3>文章分类</h3>
    <ul>
      <%# @categories.each do |cate| %>
<!--        <li>-->
          <%#= link_to root_path(category_id:cate.id) do %>
<!--            <span class="text"> <%#=cate.try(:name) %></span><span class="count" style="margin-left: 150px"><%#= cate.articles.is_show_home.size %>篇</span>-->
          <%# end %>
<!--        </li>-->
      <%# end %>
    </ul>
  </div>
  <div class="widget widget_category">
    <h3>归档</h3>
    <ul>
      <%# @time_file.each do |k,v| %>
<!--        <li>-->
          <%#= link_to root_path(create_time:k.strftime("%Y-%m-%d")) do %>
<!--            <span class="text"> <%#= k.strftime("%Y年%m月") %></span><span class="count" style="margin-left: 150px"><%#= v.size %>篇</span>-->
          <%# end %>
<!--        </li>-->
      <%# end %>

    </ul>
  </div>
  <div class="widget widget_sentence">
    <h3>标签云</h3>
    <ul>
      <%# @tags.each do |tag| %>
<!--        <li>-->
          <%#= link_to root_path(tag_id:tag.id) do %>
<!--            <%#= tag.try(:name) %> <span class="badge"><%#= tag.articles.is_show_home.size %></span>-->
          <%# end %>
<!--        </li>-->
      <%# end %>
    </ul>
  </div>
</div>